<script>
    var displayText = function()
    {
        document.getElementById('batman').innerHTML = "NA NA NA NA BATMAN!";
        console.log('display text log');
        document.getElementById('robin').innerHTML = "Well Hello";
    };

</script>

<body onload="displayText();">
<div data-mage-init='{"Milton_JavascriptInit/example" : {}}'> One Div </div>


<span id="batman">  </span>

<h1 id="robin"> </h1>

</body>
